# Generated by Django 5.1.5 on 2025-01-28 17:31

from django.db import migrations


def create_device_code_oauth_client(apps, schema_editor):
    Client = apps.get_model("allauth_idp_oidc", "Client")
    Client.objects.create(
        name="resonant-cli-oauth-client-example",
        id="jUQhgOTQYiG6hmNSvaodOGJeriAqA1anqo8WFjCw",
        scopes="openid",
        type="public",
        grant_types="urn:ietf:params:oauth:grant-type:device_code",
        redirect_uris="http://127.0.0.1:8000/",
        response_types="code",
        skip_consent=False,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("allauth_idp_oidc", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_device_code_oauth_client),
    ]
